# Syncs from upstream and deploys latest to Open-VSX

name: CI/CD to Open-VSX

# Run once a month
on:
  schedule:
  - cron: '0 0 1 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  fetch-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
#       with:
#         node-version: 14
  
    - name: Rebase Upstream
      # You may pin to the exact commit or the version.
      # uses: imba-tjd/rebase-upstream-action@3727d50bfd7062fb794dcb81268451bdbe9ff5c0
      uses: imba-tjd/rebase-upstream-action@0.5
      with:
        # <user>/<repo> or the full HTTP URL
        upstream: ArtisanByteCrafter/VSCodePopTheme
        # The upstream branch that is rebased on
        branch: master
        # Greater than the number of commits the upstream made in a period
        depth: 100
        # Do the force push in this action
        push: true
        
    - name: Publish Extension to Open-VSX
      # You may pin to the exact commit or the version.
      # uses: HaaLeo/publish-vscode-extension@aae4c55fd9e724685834ff0a9488ad57c8f3ecf1
      uses: HaaLeo/publish-vscode-extension@v0
      with:
        # Personal access token
        pat: ${{ secrets.OPEN_VSX_TOKEN }}
#         dryRun: true
